export const listings = [
    {
        title: "Cozy Beachfront Cottage",
        description: "Relax in a cozy beachfront cottage with stunning ocean views.",
        image: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?auto=format&fit=crop&w=800&q=60",
        price: 1500,
        location: "Malibu",
        country: "United States",
    },
    {
        title: "Modern Loft in Downtown",
        description: "Stylish loft in the heart of downtown.",
        image: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=800&q=60",
        price: 1200,
        location: "New York City",
        country: "United States",
    },
    {
        title: "Mountain Retreat",
        description: "Peaceful cabin surrounded by mountains and nature.",
        image: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=800&q=60",
        price: 1000,
        location: "Aspen",
        country: "United States",
    },
    {
        title: "Historic Villa in Tuscany",
        description: "Classic Italian villa with vineyard views.",
        image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=60",
        price: 2500,
        location: "Florence",
        country: "Italy",
    },
    {
        title: "Treehouse Getaway",
        description: "Unique treehouse stay among tall trees.",
        image: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=800&q=60",
        price: 800,
        location: "Portland",
        country: "United States",
    },
    {
        title: "Beachfront Paradise",
        description: "Step directly onto white sandy beaches.",
        image: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?auto=format&fit=crop&w=800&q=60",
        price: 2000,
        location: "Cancun",
        country: "Mexico",
    },
    {
        title: "Rustic Lake Cabin",
        description: "Cabin beside a peaceful lake.",
        image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=60",
        price: 900,
        location: "Lake Tahoe",
        country: "United States",
    },
    {
        title: "Luxury City Penthouse",
        description: "Penthouse with panoramic city skyline views.",
        image: "https://images.unsplash.com/photo-1622396481328-9b1b78cdd9fd?auto=format&fit=crop&w=800&q=60",
        price: 3500,
        location: "Los Angeles",
        country: "United States",
    },
    {
        title: "Private Island Retreat",
        description: "Exclusive island escape with turquoise waters.",
        image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=60",
        price: 10000,
        location: "Fiji",
        country: "Fiji",
    },
    {
        title: "Desert Luxury Villa",
        description: "Luxury villa oasis in the desert.",
        image: "https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=800&q=60",
        price: 5000,
        location: "Dubai",
        country: "UAE",
    },

    {
        title: "Ski Chalet",
        description: "Ski-in ski-out chalet in snowy mountains.",
        image: "https://images.unsplash.com/photo-1502784444187-359ac186c5bb?auto=format&fit=crop&w=800&q=60",
        price: 3000,
        location: "Verbier",
        country: "Switzerland",
    },
    {
        title: "Safari Lodge",
        description: "Wildlife safari experience in luxury lodge.",
        image: "https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=800&q=60",
        price: 4000,
        location: "Serengeti",
        country: "Tanzania",
    },
    {
        title: "Historic Canal House",
        description: "Classic canal house in old European city.",
        image: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=800&q=60",
        price: 1800,
        location: "Amsterdam",
        country: "Netherlands",
    },
    {
        title: "Tropical Villa",
        description: "Private tropical villa with pool.",
        image: "https://images.unsplash.com/photo-1470165301023-58dab8118cc9?auto=format&fit=crop&w=800&q=60",
        price: 2800,
        location: "Phuket",
        country: "Thailand",
    },
    {
        title: "Mountain View Cabin",
        description: "Cabin with stunning mountain views.",
        image: "https://images.unsplash.com/photo-1521401830884-6c03c1c87ebb?auto=format&fit=crop&w=800&q=60",
        price: 1500,
        location: "Banff",
        country: "Canada",
    },
    {
        title: "Art Deco Apartment",
        description: "Stylish art deco apartment near beach.",
        image: "https://images.unsplash.com/photo-1602088113235-229c19758e9f?auto=format&fit=crop&w=800&q=60",
        price: 1600,
        location: "Miami",
        country: "United States",
    },
    {
        title: "Castle Stay",
        description: "Live like royalty in a historic castle.",
        image: "https://images.unsplash.com/photo-1585543805890-6051f7829f98?auto=format&fit=crop&w=800&q=60",
        price: 4200,
        location: "Scottish Highlands",
        country: "United Kingdom",
    },
    {
        title: "Eco Treehouse",
        description: "Eco-friendly treehouse in forest.",
        image: "https://images.unsplash.com/photo-1488462237308-ecaa28b729d7?auto=format&fit=crop&w=800&q=60",
        price: 750,
        location: "Costa Rica",
        country: "Costa Rica",
    },
    {
        title: "Lakefront Cabin",
        description: "Relax beside a peaceful lake.",
        image: "https://images.unsplash.com/photo-1578645510447-e20b4311e3ce?auto=format&fit=crop&w=800&q=60",
        price: 1200,
        location: "New Hampshire",
        country: "United States",
    },

    {
        title: "Modern Tokyo Apartment",
        description: "Minimalist apartment in Tokyo.",
        image: "https://images.unsplash.com/photo-1480796927426-f609979314bd?auto=format&fit=crop&w=800&q=60",
        price: 2000,
        location: "Tokyo",
        country: "Japan",
    },
    {
        title: "Overwater Villa",
        description: "Luxury overwater villa experience.",
        image: "https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=800&q=60",
        price: 6000,
        location: "Maldives",
        country: "Maldives",
    },
    {
        title: "Beach House",
        description: "Secluded beach house with ocean breeze.",
        image: "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?auto=format&fit=crop&w=800&q=60",
        price: 1800,
        location: "Costa Rica",
        country: "Costa Rica",
    },
    {
        title: "Luxury Ski Chalet",
        description: "Premium ski chalet in snowy resort.",
        image: "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&w=800&q=60",
        price: 4000,
        location: "Aspen",
        country: "United States",
    },
    {
        title: "Modern City Apartment",
        description: "Central city apartment with modern design.",
        image: "https://images.unsplash.com/photo-1533619239233-6280475a633a?auto=format&fit=crop&w=800&q=60",
        price: 1700,
        location: "Boston",
        country: "United States",
    },
    {
        title: "Greek Island Villa",
        description: "Beachfront villa on Greek island.",
        image: "https://images.unsplash.com/photo-1602343168117-bb8ffe3e2e9f?auto=format&fit=crop&w=800&q=60",
        price: 2600,
        location: "Mykonos",
        country: "Greece",
    },
    {
        title: "Rainforest Lodge",
        description: "Stay deep inside tropical rainforest.",
        image: "https://images.unsplash.com/photo-1493246507139-91e8fad9978e?auto=format&fit=crop&w=800&q=60",
        price: 1400,
        location: "Amazon",
        country: "Brazil",
    },
    {
        title: "Countryside Cottage",
        description: "Quiet countryside escape.",
        image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=60",
        price: 950,
        location: "Cotswolds",
        country: "United Kingdom",
    },
    {
        title: "Cliffside Ocean Villa",
        description: "Dramatic ocean views from cliffside.",
        image: "https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=800&q=60",
        price: 5200,
        location: "Santorini",
        country: "Greece",
    },
];